### ISSUE TITLE
Doesn't allow setting sr/screenResolution

### ISSUE THREAD

**Issue by BrianGeppert** [GoogleChrome/chrome-platform-analytics#30]
I'd like to be able to scale the `screenResolution` parameter by the `devicePixelRatio` to give more useful values.  Would this be possible?

**Comment by stevogotchi** [comment]
Can you provide a little more context? Do you want to override the default system information that gets sent with a hit? Maybe you can explain how this is useful, or more concretely what type of decision making you're after.

More information will help us understand and evaluate your request.

**Comment by stevogotchi** [comment]
Haven't heard back. Feel free to reopen the issue if you can provide the requested details.
