### ISSUE TITLE
Support events from browser action when the popup closes?

### ISSUE THREAD

**Issue by marcboscher** [GoogleChrome/chrome-platform-analytics#31]
I am tracking a button click within the popup of Chrome extension's browser action. But the button click effectively also closes the popup (window.close). Will the event ALWAYS be send to GA or is there a race condition here?

Quick tests show the event is making it to GA, but is it just luck? Or is there a mechanism in CPA that ensures the XHR request is sent even though the window is closed?

The same applies to tracking a link that opens a new page/tab

Thanks!

**Comment by stevogotchi** [comment]
There's a race. If you want to ensure the hit is sent, close the window from a callback.

E.g.

tracker.send(allDoneNowHit).addCallback(
    function() {
       this.closeMe();
    }.bind(this));

**Comment by marcboscher** [comment]
Alright thanks, the info online on this is very confusing and never specific to Chrome extensions. I was starting to believe in magic...

1. will the callback be called even if the tracking is disabled (not permitted)?
2. Would you like me to a add a short section on the wiki regarding callbacks?

**Comment by stevogotchi** [comment]
1) The callback is always called "when processing 
2) Sure!
