### ISSUE TITLE
Set `anonymizeIp`

### ISSUE THREAD

**Issue by rjkronemeijer** [GoogleChrome/chrome-platform-analytics#36]
To conform with EU cookie law settings, I want to set `anoymizeIp` (`aip`). In UA it is done with `ga('set', 'anonymizeIp', true);` and I see the string in the CPA js, but I don't know how to set it.

**Comment by stevogotchi** [comment]
Okay. This has been implemented (but not pushed yet) as Tracker#anonymizeIps(). The change will be available once Tyler pushes the update. Reassigning.

**Comment by MatrixFrog** [comment]
60dd907785602f5df04d001f60a5f63a6022bde2 is now on Github.

**Comment by stevogotchi** [comment]
We'll need to make a new release.
