### ISSUE TITLE
Export analytics.createDimensionParam() and analytics.createMetricParam()

### ISSUE THREAD

**Issue by ianjoneill** [GoogleChrome/chrome-platform-analytics#37]
```analytics.createDimensionParam()``` and ```analytics.createMetricParam()``` are listed as global functions on http://googlechrome.github.io/chrome-platform-analytics/namespace_analytics.html however they are not exported in export_symbols.js.

I would make a pull-request to fix this myself, but I cannot work out how to compile the project (I can't see any compilation instructions in the wiki).

**Comment by stevogotchi** [comment]
Sorry about the delayed response. For some reason, I missed your post.

We're using closure compiler. Tyler, do you have cycles to post compilation instructions?

**Comment by MatrixFrog** [comment]
I'm not sure if we have good instructions for open source users. Might be easier for us to just bring the PR into Google and submit it and then MOE-push it back out.

**Comment by ianjoneill** [comment]
Bumping visibility of PR #41.
