### ISSUE TITLE
Custom Dimensions not working

### ISSUE THREAD

**Issue by bwigoder** [GoogleChrome/chrome-platform-analytics#38]
I've tried defining custom dimensions using .dimension(x, y), e.g.

tracker.send(analytics.EventBuilder.builder().dimension(1, 'value').category(category).action(action))

but the custom dimension does not appear in the post request

**Comment by MatrixFrog** [comment]
The API changed in https://github.com/GoogleChrome/chrome-platform-analytics/commit/da6bf94d12b92346e59d2ba09528833fd94814d4 to take an object:

`eventBuilder.dimension({index: 1, value: 'value'});`

The docs at http://googlechrome.github.io/chrome-platform-analytics/ are sadly out of date. I'll file another bug to fix that.

**Comment by bwigoder** [comment]
@MatrixFrog - is this interchangable:

tracker.set('dimension1','value');

**Comment by MatrixFrog** [comment]
I don't remember, to be honest, but I think so?
