### ISSUE TITLE
Enable advertising features

### ISSUE THREAD

**Issue by jarrodek** [GoogleChrome/chrome-platform-analytics#40]
Hi,
GA have a possibility to enable advertising features which enable demographic report. When you enable this feature in Admin it tells you that you need to alter your code. There's no equivalent action in CPA. Is there an option to enable it somehow right now? And, if not, if this can be put on a roadmap to the CPA? It would be nice feature to have.

Thanks.

**Comment by stevogotchi** [comment]
As I understand it most of the advertising, especially demographics, depend on cookies. Since cookies are unsupported in CPA, I believe this wouldn't be possible.

If my understanding is incorrect, then we'd be open to accepting patches.
