### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by erlendorf** [GoogleChrome/chrome-platform-analytics#43]
The How-To currently [says](https://github.com/GoogleChrome/chrome-platform-analytics/wiki#how-to):

> The permissions in your app's manifest file, manifest.json, must include permission to communicate with Google Analytics ...

> ```
> "permissions": [
>   "https://www.google-analytics.com/", ...
> ```

It would be better to use Content Security Policy instead, if this is possible.

**Comment by DaddingtonPalace** [comment]
Thanks for the suggestion. We're not planning on taking up any new feature requests.
