### ISSUE TITLE
using in chrome app background/event page prevents it from going inactive

### ISSUE THREAD

**Issue by kzahel** [GoogleChrome/chrome-platform-analytics#44]
Once you load the google-analytics-bundle.js into an event/background page, it will never go "inactive", which an event page should do when there are no pending callbacks, etc.

Probably I just need to run my GA code in a hidden window which I create/destroy on demand, but perhaps there is a better solution.

**Comment by DaddingtonPalace** [comment]
This is probably a question for chromium-dev. The background page should go inactive. I recall that in certain IO intensive situations it will not, but if I recall correctly only disk IO will keep the background from going inactive.
