### ISSUE TITLE
 TypeError: Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by demisx** [GoogleChrome/chrome-platform-analytics#45]
I am seeing the following error in my Chrome dev tools console (Version 50.0.2661.102 (64-bit) on Mac OS X):

```
Uncaught TypeError: Cannot read property 'clientWidth' of null
  Z.ac @ google-analytics-bundle.js:68
  (anonymous function) @ rscript.js:1
```

The screenshot of the error:
![screen shot 2016-06-07 at 11 28 32 am](https://cloud.githubusercontent.com/assets/4452412/15869859/fd997906-2ca2-11e6-8b55-a861f15365e8.jpg)

Any idea how can I get rid of it? This error interferes with my development. Thank you.

**Comment by DaddingtonPalace** [comment]
The library is attempting to include standard client dimensions.

https://github.com/GoogleChrome/chrome-platform-analytics/blob/master/src/internal/google_analytics_service.js#L121

Seems like closure is holding a null window object. Tyler? Is this a known issue with Chrome or Closure?

**Comment by MatrixFrog** [comment]
Maybe that happens if you run this from the background page instead of the "app" page?
