### ISSUE TITLE
Provide unminified version or instructions on how to compile src

### ISSUE THREAD

**Issue by sawyerh** [GoogleChrome/chrome-platform-analytics#47]
I'm using the bundle in a browser extension which is compatible with Chrome, Firefox, and Opera. As part of the approval process for the Firefox and Opera extension, you're required to provide a link to the unminified versions of any library you use in your code. 

Can you please add the unminified version or provide instructions on how to compile the code in the `src` directory?

**Comment by MatrixFrog** [comment]
The unminified version is what's on this github repo. It's compiled using Closure Compiler (https://github.com/google/closure-compiler) and Google's internal build system, so it might be tricky for you to compile it yourself and get identical output. It would be helpful if someone can compile it using the open-source Closure Compiler, compare the result to ours, and if there are slight differences we can probably tweak some compiler flags to make them match, or something.
