### ISSUE TITLE
Screen type name (the "t" parameter)

### ISSUE THREAD

**Issue by jarrodek** [GoogleChrome/chrome-platform-analytics#48]
I know that Chrome apps are deprecated but I have an issue with my existing app.
I've migrated to different GA library. I wrote a web component to support GA on different platforms like Chrome App, electron etc. 
I was using measurement protocol reference to build the hit. 2 days ago I've updated my app and I just noticed 2x increase in number of users.
So I started analysing what happened. 

After analysing parameters map produced by both CPA and my library I noticed that CPA uses undocumented value for "t" parameter (hit type). CPA's value for screen view is `appview` while documented value is `screenview`. However GA hit builder (https://ga-dev-tools.appspot.com/hit-builder/) shows that both parameters are valid.

Could it be responsible for lower number of users reported before the change? For example could GA server reject some of the hits because of incorrect value? Or maybe could it affect somehow the results?

Finally, is CPA somehow is sampling hits so not all are sent to the GA server?

I'm looking for an answer for a inconsistency in the reports after the change.
I've prepared a summary of hits that are send from both versions of the app:
https://docs.google.com/spreadsheets/d/1FCx27_yzz9kJWssAiLdw5Aj1r5_bYYV1S8UthzmkxjE/edit?usp=sharing
I followed the same path in both cases and recorded what has been sent. Maybe this help with finding the problem.

**Comment by DaddingtonPalace** [comment]
The library features rate limiting and user sampling:
- [rate_limiting_channel.js](https://github.com/GoogleChrome/chrome-platform-analytics/blob/master/src/internal/rate_limiting_channel.js)
- [user_sampling_channel.js](https://github.com/GoogleChrome/chrome-platform-analytics/blob/master/src/internal/user_sampling_channel.js)

I can't really provide any advice on the "t" parameter, other than to say that "appview" was the value what we selected after consultation with the GA team when the library was first developed. If you want to continue your inquiry into that parameter and possible impacts on reporting, I think you'd get more mileage on the Google Analytics forums for measurement protocol.

Hope that helps!

**Comment by jarrodek** [comment]
Thanks. It is helping.
