### ISSUE TITLE
Don't understand how to identify individual users

### ISSUE THREAD

**Issue by sylvandrift** [GoogleChrome/chrome-platform-analytics#50]
How do I identify individual users?
Users on my application are currently being tied to sessions.
So for instance I have 250 sessions recorded and 256 recorded users, even though I only have 7 people using the test extension currently.

**Comment by DaddingtonPalace** [comment]
The library offers a subset of functionality offered by the Google Analytics service. The support offered is documented on the wiki (https://github.com/GoogleChrome/chrome-platform-analytics/wiki). Anything not covered by the wiki is either unsupported, undocumented, or documented by the Google Analytics team's documentation.
