### ISSUE TITLE
Enable tracking by User-ID

### ISSUE THREAD

**Issue by devesh** [GoogleChrome/chrome-platform-analytics#9]
https://support.google.com/analytics/answer/3123663

Build it in by default using an id unique to the logged in Chrome user (by writing a UUID to chrome.storage.sync for example) or possibly allow the client to set a User-ID manually.

**Comment by apexskier** [comment]
I'm getting the following error when setting the userId.

```
Error: userId is not a valid parameter name.
```

I'm using it like this:

```js
var service = analytics.getService('appname');
var tracker = service.getTracker('UA-XXXXX-X');
...
tracker.set('userId', uuid);
```

**Comment by apexskier** [comment]
Whoops, my install had cached to an old version. Ignore my previous comment.

**Comment by jaysonminard** [comment]
In Bower, still stuck at 1.3.0, jspm install brings this version, not 1.6.x from github

**Comment by stevogotchi** [comment]
Latest version listed in the bower file is 1.6.0.
https://github.com/GoogleChrome/chrome-platform-analytics/blob/master/bower.json

Is there something else we need to do to publish the update for bower?

On Tue, Jun 30, 2015 at 9:55 PM, Jayson Minard <notifications@github.com>
wrote:

> In Bower, still stuck at 1.3.0, jspm install brings this version, not
> 1.6.x from github
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/chrome-platform-analytics/issues/9#issuecomment-117433712>
> .
>



-- 
Steve McKay | Eng. | smckay@google.com | 310-359-8331
